services:
  - type: web
    name: score-skill
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate && gunicorn core.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9